#!/bin/bash
# Uses format script to create 4 terminals autosized

xfce4-terminal
./format -l

xfce4-terminal -e "bash -c 'htop; exec bash'"
./format -mt

xfce4-terminal -e "bash -c 'cat ~/.geo.txt; exec bash'"
./format -rt

xfce4-terminal -e "bash -c 'cat ~/.banksy.txt; exec bash'"
./format -mb

